baseURL: "https://michal.piekarczyk.xyz/"
title: "michal.piekarczyk.xyz"
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: true

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true


params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: michal.piekarczyk.xyz
  description: "because why not"
  keywords: [Blog, Portfolio, PaperMod]
  author: Michal Piekarczyk
  DateFormat: "2022-02-23"
  defaultTheme: dark  # auto, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false


  # assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    # favicon: "<link / abs url>"
    # favicon16x16: "<link / abs url>"
    # favicon32x32: "<link / abs url>"
    # apple_touch_icon: "<link / abs url>"
    # safari_pinned_tab: "<link / abs url>"

menu:
  main:
    - identifier: about
      name: about
      url: /en/about/
      weight: 10
    - identifier: handy
      name: handy
      url: /en/handy/
      weight: 10
    - identifier: posts
      name: posts
      url: /en/post/
      weight: 10
    - identifier: projects
      name: projects
      url: /en/project/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: example
      name: example.org
      url: https://example.org
      weight: 30
